<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="RestfulBooker"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="0.787">
    <properties></properties>

            <testcase
                name="testGetFillo"
                time="0.787"
                classname="com.api.misc.TestFillo">

            <failure type="com.codoid.products.exception.FilloException" message="Invalid Query - SELECT * FROM SHEET1 WHERE ID = BASEURL;">
                <![CDATA[com.codoid.products.exception.FilloException: Invalid Query - SELECT * FROM SHEET1 WHERE ID = BASEURL;
                com.codoid.products.parser.SelectQueryParser.initializeQuery(SelectQueryParser.java:46)com.codoid.products.fillo.Select.getRecordset(Select.java:44)com.codoid.products.fillo.Connection.executeQuery(Connection.java:64)com.api.utils.FilloUtil.fetchDataFromXLSX(FilloUtil.java:18)com.api.misc.TestFillo.testGetFillo(TestFillo.java:11)java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)java.base/java.lang.reflect.Method.invoke(Method.java:580)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)java.base/java.util.ArrayList.forEach(ArrayList.java:1596)org.testng.TestRunner.privateRun(TestRunner.java:819)org.testng.TestRunner.run(TestRunner.java:619)org.testng.SuiteRunner.runTest(SuiteRunner.java:443)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)org.testng.SuiteRunner.run(SuiteRunner.java:336)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)org.testng.TestNG.runSuitesLocally(TestNG.java:1228)org.testng.TestNG.runSuites(TestNG.java:1134)org.testng.TestNG.run(TestNG.java:1101)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </failure>
    </testcase>


</testsuite>
